Solve this system of linear equation.
4x1 + 3x2- 5x3 = 2
-2x1- 4x2 + 5x3 = 5
8x1 + 8x2 = -3
Constraint : Solution should be generic so that it can be used to solve linear equations with any number of variable.
- Print the determinant of the matix | A |.
- Print the inverse matrix (A-1).

In [ ]:
#using numpy
import numpy as np
A = np.array([[4, 3, -5], [-2, -4, 5], [8, 8, 0]])
B = np.array([2, 5, -3])
x = np.linalg.solve(A, B)
x

array([ 2.20833333, -2.58333333, -0.18333333])

In [ ]:
#Without numpy
import sys
n = int(input("Enter number of variables:"))
A = []
for i in range(n):
    row = list(map(int, input().strip().split()))
    A.append(row)
B = []
print("Enter B:")
for i in range(n):
  inp =  int(input("row"))
  B.append([inp])

Enter number of variables:3
4 3 -5
-2 -4 5
8 8 0
Enter B:
row2
row5
row-3


In [ ]:
print(A)
print(B)

[[4, 3, -5], [-2, -4, 5], [8, 8, 0]]
[[2], [5], [-3]]


In [ ]:
def print_matrix(matrix):
    for row in matrix:
        print(row)

def solve_linear_system(A, B):
    n = len(A)

    # copy of A And B so that we dont edit original copy
    AM = [row[:] for row in A]
    BM = [row[:] for row in B]

    # Perform Gaussian elimination
    for fd in range(n):
        fdScaler = 1.0 / AM[fd][fd]
        for j in range(n):
            AM[fd][j] *= fdScaler
        BM[fd][0] *= fdScaler

        for i in range(n):
            if i != fd:
                crScaler = AM[i][fd]
                for j in range(n):
                    AM[i][j] -= crScaler * AM[fd][j]
                BM[i][0] -= crScaler * BM[fd][0]

    # return solution
    X = [BM[i][0] for i in range(n)]

    return X


X = solve_linear_system(A, B)

# Print the solution
print("Solution for X:")
print_matrix(X)


Solution for X:
2.2083333333333335
-2.5833333333333335
-0.18333333333333326


In [ ]:
import numpy as np

det_A = np.linalg.det(A)
print("Determinant of A:", det_A)

try:
    A_inverse = np.linalg.inv(A)
    print("Inverse of A:")
    print(A_inverse)
except np.linalg.LinAlgError:
    print("Matrix is singular, cannot find the inverse")

Determinant of A: -119.99999999999997
Inverse of A:
[[ 0.33333333  0.33333333  0.04166667]
 [-0.33333333 -0.33333333  0.08333333]
 [-0.13333333  0.06666667  0.08333333]]


In [ ]:
#Without numpy
def delete_row_column(matrix, i, j):
    rows = len(matrix)
    columns = len(matrix[0])
    return [[matrix[row][col] for col in range(columns) if col != j] for row in range(rows) if row != i]


def input_square_matrix(order=None):
    if order == None:
        order = int(input("Enter the order of the square matrix: "))

    matrix = []
    for i in range(order):
        row = list(map(int, input("> ").split()))
        assert len(row) == order, "Number of elements entered does not match given dimensions"
        matrix.append(row)

    return matrix


def minor(matrix, i, j):
    matrix = delete_row_column(matrix, i, j)
    return det(matrix)


def det(matrix):
    assert len(matrix) == len(matrix[0]), "matrix should be square"
    order = len(matrix)

    if order == 1:
        return matrix[0][0]
    elif order == 2:
        determinant = (matrix[0][0] * matrix[1][1]) - (matrix[0][1] * matrix[1][0])  # ad - bc
        return determinant
    else:
        determinant = 0
        for i in range(order):
            coefficient = matrix[0][i]
            if i % 2 == 1:
                coefficient *= -1
            determinant += coefficient * minor(matrix, 0, i)
        return determinant


def transpose(matrix):
    rows = len(matrix)
    columns = len(matrix[0])

    return [[matrix[row][col] for row in range(rows)] for col in range(columns)]


def inv(matrix):
    assert len(matrix) == len(matrix[0]), "matrix should be square"
    order = len(matrix)

    determinant = det(matrix)
    cofactors = []
    for i in range(order):
        cofactors_row = []
        for j in range(order):
            coefficient = -1 if (i % 2) ^ (j % 2) else 1
            cofactors_row.append(coefficient * minor(matrix, i, j))
        cofactors.append(cofactors_row)

    adjugate = transpose(cofactors)
    inverse = [[element / determinant for element in row] for row in adjugate]
    return inverse
print("Determinant =",det(A))
print("Inverse:")
result  = inv(A)
for row in result:
  print(row)

Determinant = -120
Inverse:
[0.3333333333333333, 0.3333333333333333, 0.041666666666666664]
[-0.3333333333333333, -0.3333333333333333, 0.08333333333333333]
[-0.13333333333333333, 0.06666666666666667, 0.08333333333333333]
